from __future__ import annotations

from typing import Any, Mapping, Protocol, Sequence, runtime_checkable

from assetgraph.domain.models import AssetHypothesis, DecisionObject, Event, Observation


@runtime_checkable
class AssetGraphRepository(Protocol):
    def put_observation(self, observation: Observation) -> bool:
        """Persist observation. Returns True if inserted, False if idempotent duplicate.""" ...

    def get_observation(self, observation_id: str) -> Observation | None: ...

    def put_asset(self, asset: AssetHypothesis) -> None: ...

    def get_asset(self, asset_id: str) -> AssetHypothesis | None: ...

    def list_assets(self, mission_id: str) -> Sequence[AssetHypothesis]: ...

    def append_event(self, mission_id: str, event: Event) -> bool: ...

    def list_events(self, mission_id: str) -> Sequence[Event]: ...

    def put_decision_object(self, decision: DecisionObject) -> None: ...

    def get_decision_object(self, decision_object_id: str) -> Mapping[str, Any] | None: ...

    def close(self) -> None: ...
